### ISSUE TITLE
MongoServerSelectionError: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by yemredogru** [lihaibh/ditto#32]
uri: `mongodb://${process.env.DB_USER}:${process.env.DB_PASS}@cluster0.5i5dp.mongodb.net:27017`,
dbname: 'myDB',

MongoServerSelectionError: getaddrinfo ENOTFOUND cluster0.5i5dp.mongodb.net
    at Timeout._onTimeout (E:\ecommerce\node_modules\mongodb-snapshot\node_modules\mongodb\lib\core\sdam\topology.js:438:30)

I don't know why I'm getting this error, can you help?

**Comment by lihaibh** [comment]
`ENOTFOUND` means that the address `cluster0.5i5dp.mongodb.net` could not be resolved, you might dont have access to this dns

**Comment by lihaibh** [comment]
@yemredogru can i close?
